config/routes.rb
Optimus::Application.routes.draw do
  resources :trlocalidads

  resources :trnodos

  resources :tr_torres

  resources :tr_planes

  resources :preclientes

  resources :optimus

   root :to => 'optimus#index'

end

app/models/optimu.rb
class Optimu < ActiveRecord::Base
  attr_accessible :nombre
end

app/controllers/optimus_controller.rb
class OptimusController < ApplicationController
  # GET /optimus
  # GET /optimus.json
  def index
    @optimus = Optimu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @optimus }
    end
  end

  # GET /optimus/1
  # GET /optimus/1.json
  def show
    @optimu = Optimu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @optimu }
    end
  end

  # GET /optimus/new
  # GET /optimus/new.json
  def new
    @optimu = Optimu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @optimu }
    end
  end

  # GET /optimus/1/edit
  def edit
    @optimu = Optimu.find(params[:id])
  end

  # POST /optimus
  # POST /optimus.json
  def create
    @optimu = Optimu.new(params[:optimu])

    respond_to do |format|
      if @optimu.save
        format.html { redirect_to @optimu, notice: 'Optimu was successfully created.' }
        format.json { render json: @optimu, status: :created, location: @optimu }
      else
        format.html { render action: "new" }
        format.json { render json: @optimu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /optimus/1
  # PUT /optimus/1.json
  def update
    @optimu = Optimu.find(params[:id])

    respond_to do |format|
      if @optimu.update_attributes(params[:optimu])
        format.html { redirect_to @optimu, notice: 'Optimu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @optimu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /optimus/1
  # DELETE /optimus/1.json
  def destroy
    @optimu = Optimu.find(params[:id])
    @optimu.destroy 

    respond_to do |format|
      format.html { redirect_to optimus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/optimus_helper.rb
module OptimusHelper
end

app/views/optimus/_form.html.erb
<%= form_for(@optimu) do |f| %>
  <% if @optimu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@optimu.errors.count, "error") %> prohibited this optimu from being saved:</h2>

      <ul>
      <% @optimu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/optimus/edit.html.erb
<h1>Editing optimu</h1>

<%= render 'form' %>

<%= link_to 'Show', @optimu %> |
<%= link_to 'Back', optimus_path %>

app/views/optimus/index.html.erb
<h1>Listing optimus</h1>

<table>
      <tr>
          <th>Nombre</th>
      </tr>
    <% @optimus.each do |optimu| %>
      <tr>
        <td><%= optimu.nombre %></td>
        <td><%= link_to 'Show', optimu %></td>
        <td><%= link_to 'Edit', edit_optimu_path(optimu) %></td>
        <td><%= link_to 'Destroy',optimu, :confirm=> 'Are you sure?', :method =>:delete  %></td>
      </tr>
    <% end %>
</table>
<br />

<%= link_to 'New Optimu', new_optimu_path %>

app/views/optimus/new.html.erb
<h1>New optimu</h1>

<%= render 'form' %>

<%= link_to 'Back', optimus_path %>

app/views/optimus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @optimu.nombre %>
</p>


<%= link_to 'Edit', edit_optimu_path(@optimu) %> |
<%= link_to 'Back', optimus_path %>