config/routes.rb
Optimus::Application.routes.draw do
  resources :trlocalidads

  resources :trnodos

  resources :tr_torres

  resources :tr_planes

  resources :preclientes

  resources :optimus

   root :to => 'optimus#index'

end

app/models/precliente.rb
class Precliente < ActiveRecord::Base
  attr_accessible :pr_apellido, :pr_domicilio, :pr_nombre
  validates :pr_nombre, presence: {message: 'no debe estar en blanco'}
end

app/controllers/preclientes_controller.rb
class PreclientesController < ApplicationController
  # GET /preclientes
  # GET /preclientes.json
  def index
    @preclientes = Precliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @preclientes}
    end
  end 
  # GET /preclientes/1
  # GET /preclientes/1.json
    def show
    @precliente = Precliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @precliente }
    end
  end

  # GET /preclientes/new
  # GET /preclientes/new.json
  def new
    @precliente = Precliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @precliente }
    end
  end

  # GET /preclientes/1/edit
  def edit
    @precliente = Precliente.find(params[:id])
  end

  # POST /preclientes
  # POST /preclientes.json
  def create
    @precliente = Precliente.new(params[:precliente])
    
    respond_to do |format|
      if @precliente.save
        format.html { redirect_to @precliente, notice: 'Precliente was successfully created.' }
        format.json { render json: @precliente, status: :created, location: @precliente }
      else
        format.html { render action: "new" }
        format.json { render json: @precliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /preclientes/1
  # PUT /preclientes/1.json
  def update
    @precliente = Precliente.find(params[:id])

    respond_to do |format|
      if @precliente.update_attributes(params[:precliente])
        format.html { redirect_to @precliente, notice: 'Precliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @precliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preclientes/1
  # DELETE /preclientes/1.json
  def destroy
    @precliente = Precliente.find(params[:id])
    @precliente.destroy
    respond_to do |format|
      format.html { redirect_to preclientes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/preclientes_helper.rb
module PreclientesHelper
end

app/views/preclientes/_form.html.erb
<%= form_for(@precliente) do |f| %>
  <% if @precliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@precliente.errors.count, "error") %> prohibited this precliente from being saved:</h2>

      <ul>
      <% @precliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Apellido %><br />
    <%= f.text_field :pr_apellido %>
  </div>
  <div class="field">
    <%= f.label :Nombre %><br />
    <%= f.text_field :pr_nombre %><aside>- Nombre del Precliente - </aside>
  </div>
  <div class="field">
    <%= f.label :Domicilio %><br />
    <%= f.text_field :pr_domicilio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preclientes/edit.html.erb
<h1>Editing precliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @precliente %> |
<%= link_to 'Back', preclientes_path %>

app/views/preclientes/index.html.erb
<h1>Listado preclientes</h1>

<table class="table table-bordered">
  <tr>
    <th>Apellido</th>
    <th>Nombre</th>
    <th>Domicilio</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @preclientes.each do |precliente| %>
  <tr>
    <td><%= precliente.pr_apellido %></td>
    <td><%= precliente.pr_nombre %></td>
    <td><%= precliente.pr_domicilio %></td>
    <td><%= link_to 'Show', precliente %></td>
    <td><%= link_to 'Edit', edit_precliente_path(precliente) %></td>
    <td><%= link_to 'Destroy', precliente, :confirm =>'Estas Seguro de Eliminar el Precliente?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Precliente', new_precliente_path %>

app/views/preclientes/new.html.erb
<h1>Nuevo precliente</h1>

<%= render 'form' %>

<%= link_to 'Back', preclientes_path %>

app/views/preclientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Apellido:</b>
  <%= @precliente.pr_apellido %>
</p>

<p>
  <b>Nombre:</b>
  <%= @precliente.pr_nombre %>
</p>

<p>
  <b>Domicilio:</b>
  <%= @precliente.pr_domicilio %>
</p>


<%= link_to 'Edit', edit_precliente_path(@precliente) %> |
<%= link_to 'Back', preclientes_path %>