config/routes.rb
Optimus::Application.routes.draw do
  resources :trlocalidads

  resources :trnodos

  resources :tr_torres

  resources :tr_planes

  resources :preclientes

  resources :optimus

   root :to => 'optimus#index'

end

app/models/trnodo.rb
class Trnodo < ActiveRecord::Base
  attr_accessible :no_idtorres, :no_iduser, :no_ip, :no_nombre
end

app/controllers/trnodos_controller.rb
class TrnodosController < ApplicationController
  # GET /trnodos
  # GET /trnodos.json
  def index
    @trnodos = Trnodo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trnodos }
    end
  end

  # GET /trnodos/1
  # GET /trnodos/1.json
  def show
    @trnodo = Trnodo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trnodo }
    end
  end

  # GET /trnodos/new
  # GET /trnodos/new.json
  def new
    @trnodo = Trnodo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trnodo }
    end
  end

  # GET /trnodos/1/edit
  def edit
    @trnodo = Trnodo.find(params[:id])
  end

  # POST /trnodos
  # POST /trnodos.json
  def create
    @trnodo = Trnodo.new(params[:trnodo])

    respond_to do |format|
      if @trnodo.save
        format.html { redirect_to @trnodo, notice: 'Trnodo was successfully created.' }
        format.json { render json: @trnodo, status: :created, location: @trnodo }
      else
        format.html { render action: "new" }
        format.json { render json: @trnodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trnodos/1
  # PUT /trnodos/1.json
  def update
    @trnodo = Trnodo.find(params[:id])

    respond_to do |format|
      if @trnodo.update_attributes(params[:trnodo])
        format.html { redirect_to @trnodo, notice: 'Trnodo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trnodo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trnodos/1
  # DELETE /trnodos/1.json
  def destroy
    @trnodo = Trnodo.find(params[:id])
    @trnodo.destroy

    respond_to do |format|
      format.html { redirect_to trnodos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trnodos_helper.rb
module TrnodosHelper
end

app/views/trnodos/_form.html.erb
<%= form_for(@trnodo) do |f| %>
  <% if @trnodo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trnodo.errors.count, "error") %> prohibited this trnodo from being saved:</h2>

      <ul>
      <% @trnodo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :no_nombre %><br />
    <%= f.text_field :no_nombre %>
  </div>
  <div class="field">
    <%= f.label :no_ip %><br />
    <%= f.text_field :no_ip %>
  </div>
  <div class="field">
    <%= f.label :no_idtorres %><br />
    <%= f.number_field :no_idtorres %>
  </div>
  <div class="field">
    <%= f.label :no_iduser %><br />
    <%= f.number_field :no_iduser %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trnodos/edit.html.erb
<h1>Editing trnodo</h1>

<%= render 'form' %>

<%= link_to 'Show', @trnodo %> |
<%= link_to 'Back', trnodos_path %>

app/views/trnodos/index.html.erb
<h1>Listing trnodos</h1>

<table>
  <tr>
    <th>No nombre</th>
    <th>No ip</th>
    <th>No idtorres</th>
    <th>No iduser</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trnodos.each do |trnodo| %>
  <tr>
    <td><%= trnodo.no_nombre %></td>
    <td><%= trnodo.no_ip %></td>
    <td><%= trnodo.no_idtorres %></td>
    <td><%= trnodo.no_iduser %></td>
    <td><%= link_to 'Show', trnodo %></td>
    <td><%= link_to 'Edit', edit_trnodo_path(trnodo) %></td>
    <td><%= link_to 'Destroy', trnodo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trnodo', new_trnodo_path %>

app/views/trnodos/new.html.erb
<h1>New trnodo</h1>

<%= render 'form' %>

<%= link_to 'Back', trnodos_path %>

app/views/trnodos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>No nombre:</b>
  <%= @trnodo.no_nombre %>
</p>

<p>
  <b>No ip:</b>
  <%= @trnodo.no_ip %>
</p>

<p>
  <b>No idtorres:</b>
  <%= @trnodo.no_idtorres %>
</p>

<p>
  <b>No iduser:</b>
  <%= @trnodo.no_iduser %>
</p>


<%= link_to 'Edit', edit_trnodo_path(@trnodo) %> |
<%= link_to 'Back', trnodos_path %>