config/routes.rb
Optimus::Application.routes.draw do
  resources :trlocalidads

  resources :trnodos

  resources :tr_torres

  resources :tr_planes

  resources :preclientes

  resources :optimus

   root :to => 'optimus#index'

end

app/models/tr_plane.rb
class TrPlane < ActiveRecord::Base
  attr_accessible :pl_elim, :pl_importe, :pl_nombre, :pl_veloc, :us_idusuario
end

app/controllers/tr_planes_controller.rb
class TrPlanesController < ApplicationController
  # GET /tr_planes
  # GET /tr_planes.json
  def index
    @tr_planes = TrPlane.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tr_planes }
    end
  end

  # GET /tr_planes/1
  # GET /tr_planes/1.json
  def show
    @tr_plane = TrPlane.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tr_plane }
    end
  end

  # GET /tr_planes/new
  # GET /tr_planes/new.json
  def new
    @tr_plane = TrPlane.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tr_plane }
    end
  end

  # GET /tr_planes/1/edit
  def edit
    @tr_plane = TrPlane.find(params[:id])
  end

  # POST /tr_planes
  # POST /tr_planes.json
  def create
    @tr_plane = TrPlane.new(params[:tr_plane])

    respond_to do |format|
      if @tr_plane.save
        format.html { redirect_to @tr_plane, notice: 'Tr plane was successfully created.' }
        format.json { render json: @tr_plane, status: :created, location: @tr_plane }
      else
        format.html { render action: "new" }
        format.json { render json: @tr_plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tr_planes/1
  # PUT /tr_planes/1.json
  def update
    @tr_plane = TrPlane.find(params[:id])

    respond_to do |format|
      if @tr_plane.update_attributes(params[:tr_plane])
        format.html { redirect_to @tr_plane, notice: 'Tr plane was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tr_plane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tr_planes/1
  # DELETE /tr_planes/1.json
  def destroy
    @tr_plane = TrPlane.find(params[:id])
    @tr_plane.destroy

    respond_to do |format|
      format.html { redirect_to tr_planes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tr_planes_helper.rb
module TrPlanesHelper
end

app/views/tr_planes/_form.html.erb
<%= form_for(@tr_plane) do |f| %>
  <% if @tr_plane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tr_plane.errors.count, "error") %> prohibited this tr_plane from being saved:</h2>

      <ul>
      <% @tr_plane.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pl_nombre %><br />
    <%= f.text_field :pl_nombre %>
  </div>
  <div class="field">
    <%= f.label :pl_importe %><br />
    <%= f.text_field :pl_importe %>
  </div>
  <div class="field">
    <%= f.label :pl_veloc %><br />
    <%= f.text_field :pl_veloc %>
  </div>
  <div class="field">
    <%= f.label :pl_elim %><br />
    <%= f.check_box :pl_elim %>
  </div>
  <div class="field">
    <%= f.label :us_idusuario %><br />
    <%= f.number_field :us_idusuario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tr_planes/edit.html.erb
<h1>Editing tr_plane</h1>

<%= render 'form' %>

<%= link_to 'Show', @tr_plane %> |
<%= link_to 'Back', tr_planes_path %>

app/views/tr_planes/index.html.erb
<h1>Listing tr_planes</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th>Importe</th>
    <th>Velocidad</th>
    <th>Eliminado</th>
    <th>Us idusuario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tr_planes.each do |tr_plane| %>
  <tr>
    <td><%= tr_plane.pl_nombre %></td>
    <td><%= tr_plane.pl_importe %></td>
    <td><%= tr_plane.pl_veloc %></td>
    <td><%= tr_plane.pl_elim %></td>
    <td><%= tr_plane.us_idusuario %></td>
    <td><%= link_to 'Show', tr_plane %></td>
    <td><%= link_to 'Destroy', tr_plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Destroy', tr_plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tr plane', new_tr_plane_path %>

app/views/tr_planes/new.html.erb
<h1>Nuevo Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', tr_planes_path %>

app/views/tr_planes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pl nombre:</b>
  <%= @tr_plane.pl_nombre %>
</p>

<p>
  <b>Pl importe:</b>
  <%= @tr_plane.pl_importe %>
</p>

<p>
  <b>Pl veloc:</b>
  <%= @tr_plane.pl_veloc %>
</p>

<p>
  <b>Pl elim:</b>
  <%= @tr_plane.pl_elim %>
</p>

<p>
  <b>Us idusuario:</b>
  <%= @tr_plane.us_idusuario %>
</p>


<%= link_to 'Edit', edit_tr_plane_path(@tr_plane) %> |
<%= link_to 'Back', tr_planes_path %>